[build]
  command = "npm run build"
  publish = ".netlify"

[build.environment]
  NODE_VERSION = "22"

[functions]
  directory = ".netlify/functions-internal"

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301
  force = true
